### ISSUE TITLE
[1.20.1] Compatibility issue with Connector (and a calling mod) and Supplementaries

### ISSUE THREAD

**Issue by Reshy** [team-abnormals/blueprint#242] opened 2024-05-18 01:30 UTC
Crash occurs when loading into the world:
![image](https://github.com/team-abnormals/blueprint/assets/2096384/a1fafa6b-c645-456d-9405-9578719bf443)

Log:  https://pastebin.com/9dwXNjYF
Crash:  https://pastebin.com/LvTUx753

Mod List that causes the crash:
![image](https://github.com/team-abnormals/blueprint/assets/2096384/5be18e4d-b754-46eb-8b5e-f5418ba8a9e9)

**Comment by SmellyModder** [comment] 2024-05-18 03:14
I do not see how this crash relates to Blueprint.
You are better off reporting this issue to Supplementaries. Its developers may be able to interpret the crash better because that's the mod throwing the error.
I am closing this issue until evidence is discovered that points to Blueprint being the cause.

**Closed as completed by SmellyModder** 2024-05-18 03:14 UTC
