### ISSUE TITLE
Server Crash latest Blueprint version

### ISSUE THREAD

**Issue by euquinox** [team-abnormals/blueprint#221] opened 2024-03-05 15:36 UTC
hi! the server crashes on startup after updating to the latest blueprint version
is this a mod conflict or something else?

[crash-2024-03-05_15.28.11-fml.txt](https://github.com/team-abnormals/blueprint/files/14497699/crash-2024-03-05_15.28.11-fml.txt)

**Comment by ceifadorcinixtru** [comment] 2024-03-05 16:26
same here and my modernfix version is the latest

**Comment by DarthCaesium** [comment] 2024-03-05 18:45
Same on my end as well.

**Comment by CodeGiver01** [comment] 2024-03-05 22:37
Yep, Modernfix conflicts as well as Embeddium-Extras, all latest.

**Comment by RoomAlex68** [comment] 2024-03-05 23:42
I can say the same thing here

**Comment by FurryApocalypse** [comment] 2024-03-06 01:18
Go all and update your modern fix to latest version. Then re-check and give feedback please.

**Comment by euquinox** [comment] 2024-03-06 01:51
modernfix was already updated to the latest version when I submitted the issue :[
I was in the process of updating all of the mods on my server

**Comment by euquinox** [comment] 2024-03-06 03:21
doesn't work with the latest modernfix version still

server got stuck in some weird shutting down loop and it couldn't shut down on its own so I had to force stop it this time
[crash-2024-03-06_01.56.59-server.txt](https://github.com/team-abnormals/blueprint/files/14504190/crash-2024-03-06_01.56.59-server.txt)

**Comment by SmellyModder** [comment] 2024-03-06 20:30
Blueprint caused neither crash here.
The first crash is a bug with Modern Fix.
The second crash is a duplicate of https://github.com/team-abnormals/blueprint/issues/218#issuecomment-1975269702.

**Closed by SmellyModder** 2024-03-06 20:30 UTC
