### ISSUE TITLE
[1.16.5] Log spam processing recipes from server

### ISSUE THREAD

**Issue by Kaleidio** [team-abnormals/blueprint#136] opened 2022-01-12 14:40 UTC
[14:34:41] [main/ERROR]: Couldn't parse loot table minecraft:blocks/brown_carpet
java.lang.NullPointerException: null
	at com.minecraftabnormals.abnormals_core.common.loot.modification.LootModificationManager.onLootTableLoad(LootModificationManager.java:59) ~[?:3.3.0]
	
every single vanilla recipe is being output here when connecting to my modpack's server.

**Comment by SettingDust** [comment] 2022-01-14 12:32
`java.lang.NullPointerException: Cannot invoke "com.minecraftabnormals.abnormals_core.common.loot.modification.LootModificationManager.getModifiers(net.minecraft.util.ResourceLocation)" because "com.minecraftabnormals.abnormals_core.common.loot.modification.LootModificationManager.INSTANCE" is null
`

**Comment by Kaleidio** [comment] 2022-01-14 16:57
I confirm I get that log too.  shoulda uploaded latest, apologies.

**Comment by SmellyModder** [comment] 2022-01-14 19:36
These errors are caused by other mods loading loot tables too early, and a fix for this got added in the latest version of Blueprint for 1.18.
A hotfix for this issue for 1.16.5 would be good.

**Closed** 2022-01-15 17:56 UTC
Labels: Bug, Mod Conflict
