### ISSUE TITLE
Blueprint Causing Crash on new generation of chunk - 1.18.2 - blueprint-1.18.2-5.5.0.jar

### ISSUE THREAD

**Issue by Chassx2** [team-abnormals/blueprint#200] opened 2023-07-06 09:44 UTC
This isn't the first time this has happened.
I have weather2 installed as well. 

Any idea on why it's causing it?

Time: 7/6/23, 5:37 AM
Description: Exception generating new chunk

java.lang.IllegalStateException: Feature order cycle found, involved biomes: [Reference{ResourceKey[minecraft:worldgen/biome / biomesoplenty:pasture]=net.minecraft.world.level.biome.Biome@74f67cac}, Reference{ResourceKey[minecraft:worldgen/biome / wythers:badlands_canyon]=net.minecraft.world.level.biome.Biome@212650c1}]
	at net.minecraft.world.level.biome.BiomeSource.m_186727_(BiomeSource.java:136) ~[server-1.18.2-20220404.173914-srg.jar%23730!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender_forge.mixins.json:MixinBiomeSource,pl:mixin:APP:byg.mixins.json:access.BiomeSourceAccess,pl:mixin:A}
	at com.teamabnormals.blueprint.common.world.modification.ModdedBiomeSlicesManager.lambda$onServerAboutToStart$2(ModdedBiomeSlicesManager.java:104) ~[blueprint-1.18.2-5.5.0.jar%23123!/:5.5.0] {re:mixin,re:classloading}
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.0.1-jre.jar%2323!/:?] {}
	at net.minecraft.world.level.biome.BiomeSource.m_186733_(BiomeSource.java:258) ~[server-1.18.2-20220404.173914-srg.jar%23730!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender_forge.mixins.json:MixinBiomeSource,pl:mixin:APP:byg.mixins.json:access.BiomeSourceAccess,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkGenerator.m_183372_(ChunkGenerator.java:401) ~[server-1.18.2-20220404.173914-srg.jar%23730!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:standardbiomesatspawn.mixins.json:ChunkGeneratorAccess,pl:mixin:APP:standardbiomesatspawn.mixins.json:ChunkGeneratorInject,pl:mixin:APP:byg.mixins.json:access.ChunkGeneratorAccess,pl:mixin:APP:citadel.mixins.json:ChunkGeneratorMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkStatus.m_187807_(ChunkStatus.java:135) ~[server-1.18.2-20220404.173914-srg.jar%23730!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.ChunkStatus.m_187788_(ChunkStatus.java:262) ~[server-1.18.2-20220404.173914-srg.jar%23730!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$22(ChunkMap.java:589) ~[server-1.18.2-20220404.173914-srg.jar%23730!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar%2326!/:?] {}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$24(ChunkMap.java:587) ~[server-1.18.2-20220404.173914-srg.jar%23730!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[server-1.18.2-20220404.173914-srg.jar%23730!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[server-1.18.2-20220404.173914-srg.jar%23730!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[server-1.18.2-20220404.173914-srg.jar%23730!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[server-1.18.2-20220404.173914-srg.jar%23730!/:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.level.biome.BiomeSource.m_186727_(BiomeSource.java:136) ~[server-1.18.2-20220404.173914-srg.jar%23730!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender_forge.mixins.json:MixinBiomeSource,pl:mixin:APP:byg.mixins.json:access.BiomeSourceAccess,pl:mixin:A}
	at com.teamabnormals.blueprint.common.world.modification.ModdedBiomeSlicesManager.lambda$onServerAboutToStart$2(ModdedBiomeSlicesManager.java:104) ~[blueprint-1.18.2-5.5.0.jar%23123!/:5.5.0] {re:mixin,re:classloading}
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.0.1-jre.jar%2323!/:?] {}
	at net.minecraft.world.level.biome.BiomeSource.m_186733_(BiomeSource.java:258) ~[server-1.18.2-20220404.173914-srg.jar%23730!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender_forge.mixins.json:MixinBiomeSource,pl:mixin:APP:byg.mixins.json:access.BiomeSourceAccess,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkGenerator.m_183372_(ChunkGenerator.java:401) ~[server-1.18.2-20220404.173914-srg.jar%23730!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:standardbiomesatspawn.mixins.json:ChunkGeneratorAccess,pl:mixin:APP:standardbiomesatspawn.mixins.json:ChunkGeneratorInject,pl:mixin:APP:byg.mixins.json:access.ChunkGeneratorAccess,pl:mixin:APP:citadel.mixins.json:ChunkGeneratorMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkStatus.m_187807_(ChunkStatus.java:135) ~[server-1.18.2-20220404.173914-srg.jar%23730!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.ChunkStatus.m_187788_(ChunkStatus.java:262) ~[server-1.18.2-20220404.173914-srg.jar%23730!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$22(ChunkMap.java:589) ~[server-1.18.2-20220404.173914-srg.jar%23730!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar%2326!/:?] {}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$24(ChunkMap.java:587) ~[server-1.18.2-20220404.173914-srg.jar%23730!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[server-1.18.2-20220404.173914-srg.jar%23730!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[server-1.18.2-20220404.173914-srg.jar%23730!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[server-1.18.2-20220404.173914-srg.jar%23730!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[server-1.18.2-20220404.173914-srg.jar%23730!/:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
-- Chunk to be generated --

**Comment by SmellyModder** [comment] 2023-07-08 23:03
This is not a Blueprint issue and is a duplicate of https://github.com/team-abnormals/blueprint/issues/197.

**Closed by SmellyModder** 2023-07-08 23:03 UTC
