### ISSUE TITLE
Conflict with terrablender

### ISSUE THREAD

**Issue by Bananalord57** [team-abnormals/blueprint#181] opened 2022-09-23 02:37 UTC
Using:
Forge 1.18.2 - 40.1.76
blueprint 1.18.2 - 5.4.6
terrablender 1.18.2 - 1.2.0.126

When used with terrablender, no vegetation is created on world gen, this includes trees, grass, flowers, and dead bushes

**Comment by SmellyModder** [comment] 2022-09-23 14:03
Duplicate of #178
This issue got fixed in Blueprint versions 5.4.7+.

**Closed by SmellyModder** 2022-09-23 14:03 UTC
