### ISSUE TITLE
[1.18.2] Prevents BOP biomes from generating on server world?

### ISSUE THREAD

**Issue by xenornithos** [team-abnormals/blueprint#159] opened 2022-05-14 17:47 UTC
**Asking here, because the issue happened after installing Blueprint.**

I added a mod (Compat O Plenty) for a custom modpack, that also includes Biomes O Plenty. Compat O Plenty requires Blueprint. Made a personal server with this, and eventually noticed no BOP biomes were showing up. Contacted the BOP devs, didn't get much info. I tried creating many test servers for what mods could be causing this BOP biome generation issue (as it would work by itself). Using the "/locatebiome" command helps determine whether a BOP biome could be found or not. After adding Compat O Plenty (and Blueprint), and running the server two times, BOP gen stopped working during the 2nd server run (without touching any files between sessions). When they are removed, on a fresh server, BOP gen works each server session.

So, I think Blueprint is causing this issue, and am wondering how is this occurring and if there's anything that can fix this.

_Using Forge 40.0.24 (required due to using the latest OptiFine H7), Biomes O Plenty 16.0.0.109 (with TerraBlender 1.1.0.99), Blueprint 5.3.0._

**Comment by SmellyModder** [comment] 2022-05-16 23:58
Duplicate of #154.
This issue is fixed in Blueprint version [5.3.2](https://www.curseforge.com/minecraft/mc-mods/blueprint/files/3756782).

**Closed as completed by SmellyModder** 2022-05-16 23:58 UTC
Labels: Duplicate, Mod Conflict

**Comment by xenornithos** [comment] 2022-05-17 00:47
The problem with using that Blueprint version is that it requires a higher Forge version. If to change the line in the mods TOML file to use Forge version "[40,)", I get this error: "_Mixin apply failed blueprint.mixins.json:AdvancementBuilderMixin_".

**Comment by SmellyModder** [comment] 2022-05-17 00:52
Yes, I discussed that with you here: https://github.com/team-abnormals/blueprint/issues/157
I warned you there are important bug fixes that are not on Blueprint version `5.3.0`. Unfortunately, there isn't much I can do for you right now, but I advise you to use the latest version of Blueprint as soon as possible.

**Comment by xenornithos** [comment] 2022-05-17 01:06
Oh, right, I had forgotten that was posted. Thanks for the reminder.
It's unfortunate OptiFine doesn't have a release at this time for any Forge version above 40.0.24, so I guess the only solution for now is to not use one of these conflicting mods.
