### ISSUE TITLE
Suspected mod crashed my world

### ISSUE THREAD

**Issue by SlytherTheUndertaker** [team-abnormals/blueprint#247] opened 2024-07-04 19:55 UTC
Hi, I'm here to open up this issue because apparently, Blueprint seems to be a suspected mod involved in a java.lang.IllegalStateException crash error involving a biome from Quark.
[crash-2024-07-04_20.50.45-server.txt](https://github.com/user-attachments/files/16102467/crash-2024-07-04_20.50.45-server.txt)

It was working fine, but after updating Waystone and and Create:TFMG, this happened.

**Comment by Lonemind** [comment] 2024-07-04 20:41
Minecraft 1.20.1
Upgrade Aquatics 1.6.0.0
Waystones 14.1.4
Crashlog: https://mclo.gs/dnVspIY

I have the same crash. I am not using Create:TFMG but I did update both Upgrade Aquatics and Waystones just today. My crashlog seems to involve Terralith's Mantle Caves if I'm reading it right.

Minecraft freezes and the console generates a crashlog but then doesn't close Minecraft.

**Comment by SmellyModder** [comment] 2024-07-12 22:37
Not a Blueprint issue.
Duplicate of https://github.com/team-abnormals/blueprint/issues/197.

**Closed by SmellyModder** 2024-07-12 22:37 UTC
