### ISSUE TITLE
Extreme world lag

### ISSUE THREAD

**Issue by E-daw** [team-abnormals/blueprint#156] opened 2022-05-04 03:30 UTC
![image](https://user-images.githubusercontent.com/34014927/166619445-db1ddcd8-53cc-4a80-a21d-3bd2eead1420.png)

I'm not sure what mod specifically with blueprint is causing it, or if it's the library itself but there is terrbile TPS lag because of abnormal_core. I'm on version 1.16.5-3.3.1

Any known fix for this?

Thanks,

Edaw

**Comment by SmellyModder** [comment] 2022-05-04 19:33
Duplicate of #133

**Closed by SmellyModder** 2022-05-04 19:33 UTC

**Comment by nthxny** [comment] 2022-05-09 07:38
> Duplicate of #133

yeah except you didn't fix it headass
