### ISSUE TITLE
[1.20.1] Crashing with unknown mod? (large modpack)

### ISSUE THREAD

**Issue by BoardAnims** [team-abnormals/blueprint#245] opened 2024-06-22 18:56 UTC
I was planning on adding upgrade aquatic to my custom modpack, but seems like it is crashing the game on world load. It also seems to throw an error warning with the [owo library](https://modrinth.com/mod/owo-lib/versions) at the main menu, but I haven't been able to screenshot it or identify it (in the config) yet...

[latest.log](https://github.com/user-attachments/files/15937983/latest.log)

Sorry for the messy log, I really dont know how to manage mods, the blueprint errors seem to be at the very end of the log.

I also think this was done with a few other (non library) mods disabled, should I try to binary search to see which mod conflicts with bluprint?

**Comment by SmellyModder** [comment] 2024-06-22 20:19
The crash appears to be caused by Moog's Voyager Structures. This is an issue on their side and appears to be a duplicate of https://github.com/team-abnormals/blueprint/issues/226.

Also, just as advice, if you're encountering incompatibility issues between Blueprint and Fabric mods (owo library in this case), this is to be expected because Blueprint is NOT designed for Fabric. You should always report Connector-exclusive errors to Connector first.
It's very unlikely we will go out of our way to fix issues for platforms we do not support.

**Closed by SmellyModder** 2024-06-22 20:19 UTC
