### ISSUE TITLE
mod crashes my game when i try to uninstall it 

### ISSUE THREAD

**Issue by mcplayerovo** [team-abnormals/blueprint#265] opened 2024-11-22 10:56 UTC
i used this mod as a library for the Incubation mod,but now i am trying to remove it and it crashes the world whenever i try,i removed all other mods with no problem but i ad an issue with bleuprint mod. 
but somhow it doen't gve a crash log 
when i try to join thje worl it sayes the save data are crrupted whenever i remove the mod from the mc mods fiel

**Comment by SmellyModder** [comment] 2024-11-23 15:48
Sounds like a duplicate of #250

**Closed as completed by SmellyModder** 2024-11-23 15:48 UTC

**Comment by mcplayerovo** [comment] 2024-11-23 16:00
i know yet i can't figure out how to fix it .i really treied ,but since it blocke when i try to recreat the world ,i can't change the world generation settings
