### ISSUE TITLE
Crash on entering world or new world generation

### ISSUE THREAD

**Issue by abby-cadabra** [team-abnormals/blueprint#218] opened 2024-03-03 05:10 UTC
Hi there,

Adding Sullys Mod and Blueprint to a pre-existing world (with no other new mods or datapacks) caused "Errors in currently selected datapacks prevented the world from loading." Attempting to load in safe mode says the world is corrupted.

When trying to create a new world with Sullys and Blueprint installed, the screen hangs indefinitely on "preparing for world generation."

Removing Sullys and Blueprint allows the 'corrupted' world to load normally, and also allows for new world generation.

I have attached the latest crash log below, and also posted this report in the Sullys Mod page since I'm not sure which mod is the core issue.

[2024-03-03-7[1].log](https://github.com/team-abnormals/blueprint/files/14471848/2024-03-03-7.1.log)

Details:
Minecraft 1.20.1
Forge-47.2.20
Sullys 3.1.2-beta
Blueprint 1.20.1-7.0.1.jar

Happy to provide any other details as needed.

**Comment by Uraneptus** [comment] 2024-03-03 09:20
Hi, Sullys-Mod dev here. This is caused by blueprint removing important compat files that the newer sullysmod versions still use.
It will be fixed on our end with the next major release! (Can still take a good while tho)
Until then I suggest using blueprint version 7.0.0

**Comment by abby-cadabra** [comment] 2024-03-03 09:41
Thanks Uraneptus, appreciate the quick response!

**Comment by SmellyModder** [comment] 2024-03-03 19:17
Your crash report contains another issue with another mod besides Sully's Mod.

`com.finndog.mns`, which I assume is [Moogs Nether Structures](https://legacy.curseforge.com/minecraft/mc-mods/mns-moogs-nether-structures), appears to be using the same code that Repurposed Structures used in the past for its `getAllDatapacksJSONElement()` method.

The way they get all the elements from all data packs is not compatibility-safe because it assumes the type of the game's resource managers. Additionally, their method is unnecessary because it's possible without mixins.
See https://github.com/TelepathicGrunt/RepurposedStructures/issues/324

**Closed by SmellyModder** 2024-03-03 19:17 UTC
