### ISSUE TITLE
possible blueprint issue 

### ISSUE THREAD

**Issue by zmqrcoo** [team-abnormals/blueprint#208] opened 2023-10-26 20:48 UTC
i added blueprint and several mods that require it to my custom modpack, and found that if i remove them the game works perfectly fine, is there any workaround without having to remove these mods? here's the log before removing the mods that require blueprint: https://mclo.gs/HKqTCFZ

**Comment by SmellyModder** [comment] 2023-10-29 02:37
There doesn't appear to be anything in the log that suggests Blueprint is the cause other than Blueprint appearing in the stack trace for a feature order cycle error, but that's actually not Blueprint's fault.

One of the mods that depends on Blueprint is probably the cause. Have you tried running Blueprint without any of the dependent mods?

**Comment by zmqrcoo** [comment] 2023-10-29 19:23
> There doesn't appear to be anything in the log that suggests Blueprint is the cause other than Blueprint appearing in the stack trace for a feature order cycle error, but that's actually not Blueprint's fault.
> 
> One of the mods that depends on Blueprint is probably the cause. Have you tried running Blueprint without any of the dependent mods?

i did, but it still did not work.

**Comment by SmellyModder** [comment] 2023-11-04 17:32
Hmm, there could be an incompatibility between Blueprint and another mod.
Try removing mods besides Blueprint and see if the crash goes away.

**Comment by SmellyModder** [comment] 2024-03-12 16:56
Upon reinspection, it looks like your crash is a duplicate of https://github.com/team-abnormals/blueprint/issues/197.
It looks like Regions Unexplored is involved.

**Closed as completed by SmellyModder** 2024-03-12 16:56 UTC
