### ISSUE TITLE
crash on world load

### ISSUE THREAD

**Issue by TheNimbleNinja** [team-abnormals/blueprint#210] opened 2023-11-20 22:06 UTC
crash on world load
version 1.18.2
https://gist.github.com/TheNimbleNinja/694910eeb969c9331acc70f8655ba995

**Comment by SmellyModder** [comment] 2023-11-20 23:35
This is not a Blueprint issue.
Duplicate of https://github.com/team-abnormals/blueprint/issues/197

**Closed by SmellyModder** 2023-11-20 23:35 UTC
