### ISSUE TITLE
Possible WorldGen Issue?

### ISSUE THREAD

**Issue by Ginger256365455** [team-abnormals/blueprint#214] opened 2024-01-28 19:31 UTC
[crash-2024-01-28_15.18.45-server.txt](https://github.com/team-abnormals/blueprint/files/14077468/crash-2024-01-28_15.18.45-server.txt)

Attempted to make a new world on a new modpack, it appears to be blaming Blueprint but I could just be reading it wrong.

**Comment by SmellyModder** [comment] 2024-01-29 05:03
It's not a Blueprint issue.
Duplicate of #197.

**Closed by SmellyModder** 2024-01-29 05:03 UTC
