### ISSUE TITLE
update to 7.1.0 for 1.20.1

### ISSUE THREAD

**Issue by rrazfraz123** [team-abnormals/blueprint#239] opened 2024-04-28 23:21 UTC
so you team-abnormal updated neapolitan and upgrade aquatic to 1.20.1 and both don't work on it since it requires blueprint version 7.1.0 and we only have access to 7.0.3

**Comment by rrazfraz123** [comment] 2024-04-28 23:24
curseforge btw

**Comment by bageldotjpg** [comment] 2024-04-29 00:33
Duplicate of #235

**Closed by bageldotjpg** 2024-04-29 00:33 UTC
