### ISSUE TITLE
Blueprint has failed to load correctly (1.20.1 Forge)

### ISSUE THREAD

**Issue by Numerosityy** [team-abnormals/blueprint#225] opened 2024-03-12 03:42 UTC
https://paste.atlauncher.com/view/02be0788-e074-433c-978a-d8b183e3b21d

**Comment by SmellyModder** [comment] 2024-03-12 16:25
Duplicate of #223.

**Closed by SmellyModder** 2024-03-12 16:25 UTC

**Comment by Numerosityy** [comment] 2024-03-12 20:39
thanks!
